#!/usr/bin/groovy

@Library('jenkins-pipeline@v0.4.4')
import org.apache.commons.lang.StringUtils;

pipeline {
  agent {
    kubernetes {
      defaultContainer "ruby"
      yamlFile ".jenkins/ruby_build_pod.yml"
    }
  }

  environment {
    GITHUB_TOKEN = credentials('github_token')
  }

  stages {
    stage('Setup') {
      steps {
        script {
          updateGitHubStatus('clean-build', 'pending', 'Unit tests.')
          sh 'bundle install'
          sh 'bundle exec appraisal install'
        }
      }
    }

    stage('Appraisals') {
      parallel {
        stage('Current') {
          steps {
            sh 'bundle exec rspec --format RspecJunitFormatter --out spec/reports/current/rspec.xml'
          }
          post { always { junit 'spec/reports/current/rspec.xml' } }
        }

        stage('Rails 4') {
          steps {
            sh 'bundle exec appraisal rails-4 rspec --format RspecJunitFormatter --out spec/reports/rails4/rspec.xml'
          }
          post { always { junit 'spec/reports/rails4/rspec.xml' } }
        }

        stage('Rails 5') {
          steps {
            sh 'bundle exec appraisal rails-5 rspec --format RspecJunitFormatter --out spec/reports/rails5/rspec.xml'
          }
          post { always { junit 'spec/reports/rails5/rspec.xml' } }
        }

        stage('Rails 6') {
          steps {
            sh 'bundle exec appraisal rails-6 rspec --format RspecJunitFormatter --out spec/reports/rails6/rspec.xml'
          }
          post { always { junit 'spec/reports/rails6/rspec.xml' } }
        }
      }
    }
  }

  post {
    success { updateGitHubStatus('clean-build', 'success', 'Unit tests.') }
    failure { updateGitHubStatus('clean-build', 'failure', 'Unit tests.') }
  }
}

void updateGitHubStatus(String context, String status, String description) {
  gitHubStatus([
    repoSlug:    'Invoca/invoca-metrics',
    sha:         env.GIT_COMMIT,
    description: description,
    context:     context,
    targetURL:   env.BUILD_URL,
    token:       env.GITHUB_TOKEN,
    status:      status
  ])
}
